//
//  MediaPlayerInteractorTests.swift
//  itunesapi_cs
//
//  Created by Alejandro Melo Domínguez on 7/29/19.
//  Copyright (c) 2019 Alejandro Melo Domínguez. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import itunesapi_cs
import XCTest

class MediaPlayerInteractorTests: XCTestCase {
    // MARK: Subject under test

    var sut: MediaPlayerInteractor!

    // MARK: Test lifecycle

    override func setUp() {
        super.setUp()
        setupMediaPlayerInteractor()
    }

    override func tearDown() {
        super.tearDown()
    }

    // MARK: Test setup

    func setupMediaPlayerInteractor() {
        sut = MediaPlayerInteractor()
    }

    // MARK: Tests

}
