//
//  SearchRouter.swift
//  itunesapi_cs
//
//  Created by Alejandro Melo Domínguez on 7/27/19.
//  Copyright (c) 2019 Alejandro Melo Domínguez. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol SearchRoutingLogic {
    func routeToDetails()
}

protocol SearchDataPassing {
    var dataStore: SearchDataStore? { get }
}

class SearchRouter: NSObject, SearchRoutingLogic, SearchDataPassing {
    weak var viewController: SearchViewController?
    var dataStore: SearchDataStore?

    // MARK: Routing

    func routeToDetails() {
        let storyboard = UIStoryboard(name: "DetailsViewController", bundle: nil)
        let destinationVC = storyboard.instantiateInitialViewController() as! DetailsViewController
        var destinationDS = destinationVC.router!.dataStore!
        passDataToDetails(source: dataStore!, destination: &destinationDS)
        navigateToDetails(source: viewController!, destination: destinationVC)
    }

    // MARK: Navigation

    func navigateToDetails(source: SearchViewController, destination: DetailsViewController) {
        source.show(destination, sender: nil)
    }

    // MARK: Passing data

    func passDataToDetails(source: SearchDataStore, destination: inout DetailsDataStore) {
        destination.media = source.selectedMedia
    }
}
