//
//  SearchPresenter.swift
//  itunesapi_cs
//
//  Created by Alejandro Melo Domínguez on 7/27/19.
//  Copyright (c) 2019 Alejandro Melo Domínguez. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SearchPresentationLogic {
    func displayResults(response: Search.Response)
    func displayMediaDetails(response: Search.DetailsResponse)
    func displayLoadingIndicator()
    func dismissLoadingIndicator()
}

class SearchPresenter: SearchPresentationLogic {
    weak var viewController: SearchDisplayLogic?

    func displayResults(response: Search.Response) {
        let medias = response.medias
        let viewModel = Search.ViewModel(medias: medias)

        if medias.isEmpty {
            viewController?.displayNoResults()
        } else {
            viewController?.displayResults(viewModel: viewModel)
        }
    }

    func displayMediaDetails(response: Search.DetailsResponse) {
        let viewModel = Search.DetailsViewModel(media: response.media)
        viewController?.routeToMediaDetails(viewModel: viewModel)
    }

    func displayLoadingIndicator() {
        viewController?.showLoadingIndicator()
    }

    func dismissLoadingIndicator() {
        viewController?.hideLoadingIndicator()
    }
}
