//
//  MediaPlayerModels.swift
//  itunesapi_cs
//
//  Created by Alejandro Melo Domínguez on 7/29/19.
//  Copyright (c) 2019 Alejandro Melo Domínguez. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum MediaPlayer {
    // MARK: Use cases

    struct CloseViewModel {
        let animated: Bool
    }

    struct PlayRequest {
        let media: Media
    }
    
    struct PlayResponse {
        let media: Media
    }

    struct PlayViewModel {
        let trackName: String
        var coverImageUrl: URL?
    }
}
