//
//  MediaPlayerRouter.swift
//  itunesapi_cs
//
//  Created by Alejandro Melo Domínguez on 7/29/19.
//  Copyright (c) 2019 Alejandro Melo Domínguez. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol MediaPlayerRoutingLogic {
    func dismissPopup(animated: Bool)
}

protocol MediaPlayerDataPassing {
    var dataStore: MediaPlayerDataStore? { get }
}

class MediaPlayerRouter: NSObject, MediaPlayerRoutingLogic, MediaPlayerDataPassing {
    weak var viewController: MediaPlayerViewController?
    var dataStore: MediaPlayerDataStore?
    
    func dismissPopup(animated: Bool) {
        viewController?.dismiss(animated: animated, completion: nil)
    }
}
