//
//  MediaPlayerPresenter.swift
//  itunesapi_cs
//
//  Created by Alejandro Melo Domínguez on 7/29/19.
//  Copyright (c) 2019 Alejandro Melo Domínguez. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MediaPlayerPresentationLogic {
    func presentSomething(response: MediaPlayer.Something.Response)
}

class MediaPlayerPresenter: MediaPlayerPresentationLogic {
    weak var viewController: MediaPlayerDisplayLogic?

    // MARK: Do something

    func presentSomething(response: MediaPlayer.Something.Response) {
        let viewModel = MediaPlayer.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
}
