//
//  DetailsModels.swift
//  itunesapi_cs
//
//  Created by Alejandro Melo Domínguez on 7/29/19.
//  Copyright (c) 2019 Alejandro Melo Domínguez. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Details {
    // MARK: Use cases

    struct Request {
        let media: Media
    }

    struct Response {
        let album: Album
    }

    struct ViewModel {
        let artistName: String
        let albumName: String
        var albumCoverImage: URL?
    }
}
