//
//  DetailsPresenter.swift
//  itunesapi_cs
//
//  Created by Alejandro Melo Domínguez on 7/29/19.
//  Copyright (c) 2019 Alejandro Melo Domínguez. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailsPresentationLogic {
    func presentAlbumDetails(response: Details.Response)
    func presentAlbumDetailsErrorMessage()
}

class DetailsPresenter: DetailsPresentationLogic {
    weak var viewController: DetailsDisplayLogic?

    // MARK: Do something

    func presentAlbumDetails(response: Details.Response) {
        var viewModel = Details.ViewModel(
            artistName: response.album.albumInfo?.artistName ?? "",
            albumName: response.album.albumInfo?.collectionName ?? "",
            albumCoverImage: nil,
            tracks: response.album.tracks
        )

        if let artworkUrl = response.album.albumInfo?.urlForArtwork {
            viewModel.albumCoverImage = artworkUrl
        }

        viewController?.displayDataForAlbum(viewModel: viewModel)
    }

    func presentAlbumDetailsErrorMessage() {
        
    }
}
