//
//  DetailsViewController.swift
//  itunesapi_cs
//
//  Created by Alejandro Melo Domínguez on 7/29/19.
//  Copyright (c) 2019 Alejandro Melo Domínguez. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import AlamofireImage
import UIKit

protocol DetailsDisplayLogic: class {
    func displayDataForAlbum(viewModel: Details.ViewModel)
}

class DetailsViewController: UIViewController, DetailsDisplayLogic {
    var interactor: DetailsBusinessLogic?
    var router: (NSObjectProtocol & DetailsRoutingLogic & DetailsDataPassing)?

    @IBOutlet weak var tableView: UITableView!
    @IBOutlet weak var coverImageView: UIImageView!
    @IBOutlet weak var artistLabel: UILabel!
    @IBOutlet weak var albumLabel: UILabel!

    var album: Album?
    var tracks: [Media] = []
    
    // MARK: Object lifecycle

    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }

    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }

    // MARK: Setup

    private func setup() {
        let viewController = self
        let interactor = DetailsInteractor()
        let presenter = DetailsPresenter()
        let router = DetailsRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }

    // MARK: Routing

    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }

    // MARK: View lifecycle

    override func viewDidLoad() {
        super.viewDidLoad()

        tableView.delegate = self
        tableView.dataSource = self

        if
            let dataStore = interactor as? DetailsDataStore,
            let media = dataStore.media
        {
            let request = Details.Request(media: media)
            interactor?.fetchAlbumDetails(request: request)
        }
    }

    // MARK: Use cases
    func displayDataForAlbum(viewModel: Details.ViewModel) {
        title = viewModel.albumName
        artistLabel.text = viewModel.artistName
        albumLabel.text = viewModel.albumName

        coverImageView.af_cancelImageRequest()
        coverImageView.image = nil

        if let artworkUrl = viewModel.albumCoverImage {
            coverImageView.af_setImage(withURL: artworkUrl)
        }

        tracks = viewModel.tracks
        tableView.reloadData()
    }
}

// MARK: - UITableView

extension DetailsViewController: UITableViewDataSource {
    static let cellIdentifier = "DetailsTableViewCell"

    // MARK: Data source

    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return tracks.count
    }

    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = tableView.dequeueReusableCell(withIdentifier: DetailsViewController.cellIdentifier, for: indexPath) as! DetailsTableViewCell
        let item = tracks[indexPath.row]

        cell.trackTitle = item.trackName
        cell.trackNumber = item.trackNumber

        return cell
    }
}

extension DetailsViewController: UITableViewDelegate {

    // MARK: Delegate

    func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        tableView.deselectRow(at: indexPath, animated: true)

//        let track = tracks[indexPath.row]
//
//        let request = Details.Request(media: track)
//        interactor.didSelectMedia(request: request)
    }
}
