//
//  DetailsInteractor.swift
//  itunesapi_cs
//
//  Created by Alejandro Melo Domínguez on 7/29/19.
//  Copyright (c) 2019 Alejandro Melo Domínguez. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailsBusinessLogic {
    func fetchAlbumDetails(request: Details.Request)
}

protocol DetailsDataStore {
    var media: Media? { get set }
    var album: Album? { get set }
}

class DetailsInteractor: DetailsBusinessLogic, DetailsDataStore {
    var presenter: DetailsPresentationLogic?
    var worker: DetailsWorker? = DetailsWorker()
    var media: Media?
    var album: Album?

    // MARK: Do something

    func fetchAlbumDetails(request: Details.Request) {
        worker?.fetchAlbumDetails(media: request.media, completion: { success, album in
            self.album = album

            if success {
                let response = Details.Response(album: album)
                self.presenter?.presentAlbumDetails(response: response)
            } else {
                // TODO: Show "no details available"
            }
        })
    }
}
