//
//  DetailsInteractorTests.swift
//  itunesapi_cs
//
//  Created by Alejandro Melo Domínguez on 7/29/19.
//  Copyright (c) 2019 Alejandro Melo Domínguez. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import itunesapi_cs
import XCTest

class DetailsInteractorTests: XCTestCase {
    // MARK: Subject under test

    var sut: DetailsInteractor!

    // MARK: Test lifecycle

    override func setUp() {
        super.setUp()
        setupDetailsInteractor()
    }

    override func tearDown() {
        super.tearDown()
    }

    // MARK: Test setup

    func setupDetailsInteractor() {
        sut = DetailsInteractor()
    }

    // MARK: Tests

//    func testDoSomething() {
//        // Given
//        let spy = DetailsPresentationLogicSpy()
//        sut.presenter = spy
//        let request = Details.Something.Request()
//
//        // When
//        sut.doSomething(request: request)
//
//        // Then
//        XCTAssertTrue(spy.presentSomethingCalled, "doSomething(request:) should ask the presenter to format the result")
//    }
}
