//
//  DetailsPresenterTests.swift
//  itunesapi_cs
//
//  Created by Alejandro Melo Domínguez on 7/29/19.
//  Copyright (c) 2019 Alejandro Melo Domínguez. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import itunesapi_cs
import XCTest

class DetailsPresenterTests: XCTestCase {
    // MARK: Subject under test

    var sut: DetailsPresenter!

    // MARK: Test lifecycle

    override func setUp() {
        super.setUp()
        setupDetailsPresenter()
    }

    override func tearDown() {
        super.tearDown()
    }

    // MARK: Test setup

    func setupDetailsPresenter() {
        sut = DetailsPresenter()
    }

    // MARK: Tests
    func testPresentAlbumDetails() {
        // Given
        let album = [
            Media(
                wrapperType: "collection", // collection is used for grabbing album data
                artistName: "The artist name",
                collectionId: 1,
                collectionName: "The album name",
                kind: "kind",
                trackId: 1,
                trackName: "track 1",
                trackNumber: 1,
                artwork: "artwork",
                previewUrl: nil
            )
        ]
        let viewControllerSpy = DetailsDisplayLogicSpy()
        sut.viewController = viewControllerSpy
        let response = Details.Response(album: album)

        // When
        sut.presentAlbumDetails(response: response)

        // Then
        XCTAssertTrue(viewControllerSpy.displayDataForAlbumCalled)
    }
    
}
