//
//  DetailsViewControllerTests.swift
//  itunesapi_cs
//
//  Created by Alejandro Melo Domínguez on 7/29/19.
//  Copyright (c) 2019 Alejandro Melo Domínguez. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import itunesapi_cs
import XCTest

class DetailsViewControllerTests: XCTestCase {
    // MARK: Subject under test
    var sut: DetailsViewController!
    var window: UIWindow!

    // MARK: Test lifecycle

    override func setUp() {
        super.setUp()
        window = UIWindow()
        setupDetailsViewController()
    }

    override func tearDown() {
        window = nil
        super.tearDown()
    }

    // MARK: Test setup
    
    func setupDetailsViewController() {
        let bundle = Bundle.main
        let storyboard = UIStoryboard(name: "DetailsViewController", bundle: bundle)
        sut = (storyboard.instantiateInitialViewController() as! DetailsViewController)
    }

    func loadView() {
        window.addSubview(sut.view)
        RunLoop.current.run(until: Date())
    }

    // MARK: Tests

//    func testShouldDoSomethingWhenViewIsLoaded() {
//        // Given
//        let spy = DetailsBusinessLogicSpy()
//        sut.interactor = spy
//
//        // When
//        loadView()
//
//        // Then
//        XCTAssertTrue(spy.doSomethingCalled, "viewDidLoad() should ask the interactor to do something")
//    }
//
//    func testDisplaySomething() {
//        // Given
//        let viewModel = Details.Something.ViewModel()
//
//        // When
//        loadView()
//        sut.displaySomething(viewModel: viewModel)
//
//        // Then
//        //XCTAssertEqual(sut.nameTextField.text, "", "displaySomething(viewModel:) should update the name text field")
//    }
}
